local mode = require("nvim-scout.lib.search_mode")
local stub = require("luassert.stub")
local consts = require("nvim-scout.lib.consts")
local utils = require("spec.spec_utils")
utils:register_global_consts()
utils:register_global_logger()
describe('search mode', function ()

    before_each(function ()
        stub(vim.api, "nvim_set_hl").returns(0)
    end)

    after_each(function ()
        vim.api.nvim_set_hl:revert()
    end)

    it('adds the padding space onto it\'s display width', function ()
        local m = mode:new("Eric Mode", "E", 0, "Red")
        assert.equals(m:get_banner_display_width(), #m.name + consts.modes.padding_space)
        m = mode:new("Much longer name of string", "m", 0, "blue")
        assert.equals(m:get_banner_display_width(), #m.name + consts.modes.padding_space)
        m = mode:new("whoknows what this mode is", "w", 0, "green")
        assert.equals(m:get_banner_display_width(), #m.name + consts.modes.padding_space)
    end)

end)
