local mode = require("nvim-scout.search.search_mode")
local stub = require("luassert.stub")
local consts = require("nvim-scout.utils.consts")
local utils = require("spec.spec_utils")
utils:register_global_consts()
utils:register_global_logger()
describe('Search Mode', function ()

    before_each(function ()
        stub(vim.api, "nvim_set_hl").returns(0)
    end)

    after_each(function ()
        vim.api.nvim_set_hl:revert()
    end)

    it('adds the padding space onto it\'s display width', function ()
        local m = mode:new("Eric Mode", "E", 0, "Red", "border hl")
        assert.equals(m:get_banner_display_width(), #m.name + consts.modes.padding_space)
        m = mode:new("Much longer name of string", "m", 0, "blue")
        assert.equals(m:get_banner_display_width(), #m.name + consts.modes.padding_space)
        m = mode:new("whoknows what this mode is", "w", 0, "green")
        assert.equals(m:get_banner_display_width(), #m.name + consts.modes.padding_space)
    end)

    it('updates the border, col, window and display column when opening', function ()
        local m = mode:new("Eric Mode", "E", 0, "Red", "border hl")
        m.banner_config = {}
        m:update_banner_config(Scout_Consts.borders.ascii, 0, 1010)
        assert.equals(m.banner_config.border, Scout_Consts.borders.ascii)
        assert.equals(m.banner_config.col, 0)
        assert.equals(m.display_col, 0)
        assert.equals(m.banner_config.win, 1010)

        m:update_banner_config(Scout_Consts.borders.rounded, 34, 1011)
        assert.equals(m.banner_config.border, Scout_Consts.borders.rounded)
        assert.equals(m.banner_config.col, 34)
        assert.equals(m.display_col, 34)
        assert.equals(m.banner_config.win, 1011)
    end)

    it('adds extra padding if the banner border has background highlights', function ()
        stub(vim.api, "nvim_get_hl").returns({bg = false})
        local m = mode:new("Eric Mode", "E", 0, "Red", "border hl")
        assert.equals(m:get_extra_padding(), Scout_Consts.modes.padding_space)
        stub(vim.api, "nvim_get_hl").returns({bg = true})
        assert.equals(m:get_extra_padding(), Scout_Consts.modes.padding_space + 1)
    end)

end)
